// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Authentication JWT 
export const SIGNUP_OK = 'SIGNUP_OK';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_OK = "LOGIN_OK"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const USER_LOADED_OK = "USER_LOADED_OK"
export const USER_LOADED_FAIL = "USER_LOADED_FAIL"

export const ACTIVATION_OK = "ACTIVATION_OK"
export const ACTIVATION_FAIL = "ACTIVATION_FAIL"

export const SET_AUTH_LOADING="SET_AUTH_LOADING"
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const AUTHENTICATED_OK = "AUTHENTICATED_OK"
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL"

export const REFRESH_OK = "REFRESH_OK"
export const REFRESH_FAIL = "REFRESH_FAIL"

export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_OK="RESET_PASSWORD_OK"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"

export const RESET_PASSWORD_CONFIRM_OK="RESET_PASSWORD_CONFIRM_OK"
export const RESET_PASSWORD_CONFIRM_FAIL="RESET_PASSWORD_CONFIRM_FAIL"

// Products
export const PRODUCTS_HOME_OK="PRODUCTS_HOME_OK"
export const PRODUCTS_HOME_FAIL="PRODUCTS_HOME_FAIL"

export const PRODUCTS_OK="PRODUCTS_OK"
export const PRODUCTS_FAIL="PRODUCTS_FAIL"

export const PRODUCT_OK="PRODUCT_OK"
export const PRODUCT_FAIL="PRODUCT_FAIL"

// Categories

export const CATEGORIES_OK="CATEGORIES_OK"
export const CATEGORIES_OK_FAIL="CATEGORIES_OK_FAIL"

// Categories

export const BRANDS_OK="BRANDS_OK"
export const BRANDS_OK_FAIL="BRANDS_OK_FAIL"


// Carrito Local (frontend)
export const ADD_ITEM = 'ADD_ITEM';

export const GET_TOTAL = 'GET_TOTAL';
export const GET_ITEM_TOTAL = 'GET_ITEM_TOTAL';
export const GET_ITEMS = 'GET_ITEMS';

export const UPDATE_ITEM = 'UPDATE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';

// Cart (base de datos)
export const ADD_ITEM_OK = 'ADD_ITEM_OK';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const GET_ITEMS_OK = 'GET_ITEMS_OK';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';

export const UPDATE_ITEM_OK = 'UPDATE_ITEM_OK';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';

export const REMOVE_ITEM_OK = 'REMOVE_ITEM_OK';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';

export const EMPTY_CART_OK= 'EMPTY_CART_OK';
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL';

export const SYNCH_CART_OK = 'SYNCH_CART_OK';
export const SYNCH_CART_FAIL = 'SYNCH_CART_FAIL';

// Accounts
export const GET_ACCOUNT_OK = 'GET_ACCOUNT_OK';
export const GET_ACCOUNT_FAIL = 'GET_ACCOUNT_FAIL';

export const UPDATE_ACCOUNT_OK = 'UPDATE_ACCOUNT_OK';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';


// Wishlist
export const GET_WISHLIST_ITEMS_OK = 'GET_WISHLIST_ITEMS_OK';
export const GET_WISHLIST_ITEMS_FAIL = 'GET_WISHLIST_ITEMS_FAIL';

export const ADD_WISHLIST_ITEM_OK = 'ADD_WISHLIST_ITEM_OK';
export const ADD_WISHLIST_ITEM_FAIL = 'ADD_WISHLIST_ITEM_FAIL';

export const REMOVE_WISHLIST_ITEM_OK = 'REMOVE_WISHLIST_ITEM_OK';
export const REMOVE_WISHLIST_ITEM_FAIL = 'REMOVE_WISHLIST_ITEM_FAIL';

export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';